name: Google Compute Engineへのデプロイ

on:
  push:
    branches:
      - release
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # Dockerコンテナのビルドに必要
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # GCPの認証情報設定
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      # DockerとArtifact Registoryの認証
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev
      # DockerコンテナのビルドとPUSHを行う
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            - ${{ secrets.IMAGE_TAG }}
      # Compute Engineの再起動
      - run: gcloud compute instances update-container ${{ secrets.GCP_PROJECT_ID }} --container-image=${{ secrets.IMAGE_TAG }}
